// ignore_for_file: constant_identifier_names

enum BusinessSector {
  AGRICULTURE,
  CONSTRUCTION,
  EDUCATION,
  ENERGY,
  MANUFACTURING,
  MEDIA,
  MINING,
  TECHNOLOGY,
  TEXTILE,
  TOURISM,
  TRANSPORT,
  OTHER,
}

enum Category {
  MEDICAL,
  RELOCATION,
  REHABILITATION,
  DISASTER_RELIEF,
  LEGAL,
  CHILDCARE,
  EDUCATION,
  POVERTY_ALLEVIATION,
  EDUCATION_SUPPORT,
  ELDERLY_ASSISTANCE,
  HEALTHCARE_ASSISTANCE,
  HUMAN_RIGHTS,
  ENVIRONMENTAL_CONSERVATION,
  REFUGEE_AID,
  STARTUP_FUNDING,
  PRODUCT_LAUNCH,
  BUSINESS_EXPANSION,
  EVENT_SPONSORSHIP,
  RESEARCH_AND_DEVELOPMENT,
}

enum BankName {
  AWASH_BANK,
  ABAY_BANK,
  COMMERCIAL_BANK_OF_ETHIOPIA,
  ABYSSINIA_BANK,
  ZEMEN_BANK,
}
